### ISSUE TITLE
fluid slots can't output

### ISSUE THREAD

**Issue by friendlyhj** [DaedalusGame/RequiousFrakto#13]
My script
```zenscript
#priority 200
import mods.requious.ComponentFace;
import mods.requious.SlotVisual;
import mods.requious.Assembly;
import crafttweaker.item.IIngredient;
import crafttweaker.liquid.ILiquidStack;
import mods.requious.AssemblyRecipe;

static chlorinizer as Assembly = <assembly:chlorinizer>;
static arrowRight as SlotVisual = SlotVisual.createSimple("requious:textures/gui/assembly_gauges.png", 0, 8);

chlorinizer.setItemSlot(2, 2, ComponentFace.up(), 64).setAccess(true, false).setGroup("input");
chlorinizer.setFluidSlot(3, 2, ComponentFace.side(), 3000).setAccess(true, false).setGroup("cl");
chlorinizer.setEnergySlot(0, 2, ComponentFace.all(), 100000).setAccess(true, false).setGroup("energy");
chlorinizer.setFluidSlot(5, 2, ComponentFace.all(), 3000).setAccess(false, true).setGroup("output").pushFluid(200);
chlorinizer.setJEIItemSlot(2, 2, "input");
chlorinizer.setJEIEnergySlot(0, 2, "energy");
chlorinizer.setJEIFluidSlot(5, 2, "output");
chlorinizer.setJEIFluidSlot(3, 2, "cl");
chlorinizer.setJEIDurationSlot(4, 2, "time", arrowRight);
chlorinizer.setDurationSlot(4, 2).setGroup("time").setVisual(arrowRight);

function addChlorinizerRecipe(input as IIngredient, clAmount as int, output as ILiquidStack, energy as int, time as int) {
    val recipe as AssemblyRecipe = AssemblyRecipe.create(function(container) {
        container.addFluidOutput("output", output);
    }).requireItem("input", input)
    .requireFluid("cl", <liquid:liquidchlorine> * clAmount)
    .requireEnergy("energy", energy)
    .requireDuration("time", time);
    <assembly:chlorinizer>.addRecipe(recipe);
    <assembly:chlorinizer>.addJEIRecipe(recipe);
}

addChlorinizerRecipe(<ore:itemSilicon>, 200, <liquid:raw_sicl4> * 200, 4000, 40);
```

![image](https://user-images.githubusercontent.com/30400991/87432721-f039f180-c61a-11ea-9cd7-1294bb58f156.png)
![image](https://user-images.githubusercontent.com/30400991/87432746-f8922c80-c61a-11ea-9896-39aad7209557.png)

cannot output

**Comment by DaedalusGame** [comment]
Should be fixed

**Comment by friendlyhj** [comment]
~~Sadly, it is not fixed.~~
Sometimes, it still not works, depending on the facing of machine?
Not matching my script above, I can't extract fluid through all faces, and the only face I can extract fluid is depending on the facing of machine.

**Comment by DaedalusGame** [comment]
oh ok, that makes more sense, i was wondering when the collector degeneracy would be revealed to cause problems
i'll give it another shot
